# Generated by Django 5.1.1 on 2024-12-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarborHop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
